<?php
/**
 * @var \Dovo\HeaderImage\Block\HeaderImage $block
 */
?>
    <section class="headerImage">
        <?php if ($block->isNotificationEnabled()): ?>
            <div class="ds-disclaimer">
                <div class="inner-container">
<!--                    <p>--><?//= __('Auch wir bei DOVO feiern Weihnachten! Werksferien ab dem 22.12.2020. Eingehende Bestellugen werden wieder ab dem 04.01.2021 bearbeitet.') ?><!--</p>-->
                    <p><?= $block->getNotificationText() ?></p>
                </div>
            </div>
        <?php endif; ?>
        <div class="header-image-wrapper"
             style="background-image: url('<?php echo $this->getViewFileUrl('Dovo_HeaderImage::images/Ratgeber-header-test.jpg'); ?>');">
            <div class="header-title-wrapper" style="max-width: 1440px; margin: 0 auto; position:relative;">
                <div class="page-title"><h1><?php echo $this->getPageTitle()->getShort(); ?></h1></div>
                <!--<img class="image"
                 src="<?php //echo $this->getViewFileUrl('Dovo_HeaderImage::images/Ratgeber-header-test.jpg'); ?>"/>-->
            </div>
        </div>
        <?php

        ?>
    </section>
<?php
$h = $block->getHelperTheme();
$fx = $h->getCfg('general/effect');
$asd = $fx;

?>
