<section class="headerImage header-promo">
    <div class="ds-disclaimer">
        <div class="inner-container">
            <p><?= __('Achtung! Aktuell versenden wir aus technischen Gründen ausschließlich nach Deutschland! In wenigen Tagen wird ein Versand in andere Länder wieder möglich sein.') ?></p>
        </div>
    </div>
    <div class="header-promo-image-wrapper">
        <img src="<?= $this->getViewFileUrl('Dovo_HeaderImage::images/DOVO_BFO_1440x400_20201120_v1.jpg') ?>" alt="header-promo-image">
<!--         style="background-image: url('--><?php //echo $this->getViewFileUrl('Dovo_HeaderImage::images/DOVO_BFO_1440x400_20201120_v1.jpg'); ?><!--');">-->
    </div>
    <?php

    ?>
</section>
<?php
$h = $block->getHelperTheme();
$fx = $h->getCfg('general/effect');
$asd = $fx;

?>