<?php
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$theme = $this->helper('Infortis\Base\Helper\Data');
$helperImage = $this->helper('Infortis\Infortis\Helper\Image');
$sliderClasses = '';
$wrapperClasses = '';
$timeout = null;
$numberOfRows = null;
$thumbnails = null;

/** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
if ($exist = count($block->getItems())) {
    $type = 'crosssell';
    $class = $type;

    $imageTypeId = 'cart_cross_sell_products';
    $title = __('Großartiges Crosssell');
    $items = $block->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    $canItemsAddToCart = false;
    $showItems = 10;

    $breakpoints = $block->getBreakpoints();
    if (empty($breakpoints)) {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [992, 4], [1200, 5], [1440, 6]'; //Set default breakpoints
    }
}

if ($exist):
    ?>
    <?php // $helperAddToLinks = $this->helper('Infortis\Base\Helper\AddToLinks');

    $sliderId = "itemslider-product-{$class}";
    $collectionSize = count($items);

    //
    // Product image configuration
    // ----------------------------------------------

    // Product image dimensions
    $paramImgWidth = $this->getData('img_width');
    $paramImgHeight = $this->getData('img_height');
    if ($paramImgWidth || $paramImgHeight) {
        // Use values from params
        $imgWidth = intval($paramImgWidth);
        $imgHeight = intval($paramImgHeight);
    } else {
        // Set default values
        $imgWidth = 260;
        $imgHeight = 260;

        // If none of the image dimension parameters is set
        // then for backward compatibility check the obsolete option.
        if ($theme->getCfg('product_slider/keep_aspect_ratio')) {
            $imgHeight = null; // If keep aspect ratio, delete the height
        }
    }

    // If value equals zero or not set, replace it with null
    if (empty($imgWidth)) {
        $imgWidth = null;
    }
    if (empty($imgHeight)) {
        $imgHeight = null;
    }

    // // Alternative product image
    // $showAltImage = $theme->getCfg('category/alt_image');

    //
    // Slider configuration
    // ----------------------------------------------

    // // Single item
    // if ($collectionSize == 1)
    // {
    //     $sliderClasses .= ' single-item';
    // }

    // Breakpoints
    if (!isset($breakpoints)) // If breakpoints not set yet, set default value
    {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [992, 4], [1200, 5]';
    }

    // Responsive mode on/off and number of items
    $isResponsive = $this->getData('is_responsive');
    if ($isResponsive === null) {
        $isResponsive = true;
    }

    if (!$isResponsive) {
        $showItems = $this->getData('show_items');
        if (!$showItems) {
            $showItems = 5;
            echo $showItems;
        }
    }

    // Timeout (automatic scrolling)
    $paramTimeout = $this->getData('timeout');
    if ($paramTimeout !== null) {
        $timeout = $paramTimeout;
    }

    if ($timeout === null) {
        $timeout = intval($theme->getCfg('product_slider/timeout'));
    } else {
        $timeout = intval($timeout);
    }

    // Number of items that should move on scroll
    $move = $this->getData('move');
    if ($move === null) {
        $move = 0;
    } else {
        $move = intval($move);
    }

    // Pagination
    $pagination = $this->getData('pagination');

    // Loop
    $loop = $this->getData('loop');
    if ($loop === null) {
        $loop = $theme->getCfg('product_slider/loop');
    }

    // Speed (arrows / touch swipe)
    $speed = intval($theme->getCfg('product_slider/speed'));

    // Speed (automatic scrolling / pagination)
    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

    // Pause on mouse hover
    $pause = $theme->getCfg('product_slider/pause');

    // Lazy loading
    $lazy = $theme->getCfg('product_slider/lazy');

    //
    // Grid configuration
    // ----------------------------------------------

    // Rows

    if (empty($numberOfRows)) {
        $numberOfRows = 1;
    } else {
        $numberOfRows = intval($numberOfRows);
    }

    // Display as thumbnails

    if (!empty($thumbnails)) {
        $thumbnails = strtolower($thumbnails);

        if ($thumbnails === 'xs') {
            if ($paramImgWidth === null && $paramImgHeight === null) {
                $imgWidth = 80;
                $imgHeight = 80;
            }
        } elseif ($thumbnails === 's') {
            if ($paramImgWidth === null && $paramImgHeight === null) {
                $imgWidth = 100;
                $imgHeight = 100;
            }
        } elseif ($thumbnails === 'm') {
            if ($paramImgWidth === null && $paramImgHeight === null) {
                $imgWidth = 150;
                $imgHeight = 150;
            }
        } elseif ($thumbnails === 'l') {
            if ($paramImgWidth === null && $paramImgHeight === null) {
                $imgWidth = 200;
                $imgHeight = 200;
            }
        } else {
            // Set defaults
            $thumbnails = 's';
            if ($paramImgWidth === null && $paramImgHeight === null) {
                $imgWidth = 100;
                $imgHeight = 100;
            }
        }

        $wrapperClasses .= ' items-grid-thumbnails items-grid-thumbnails-' . $thumbnails;
        $imageTypeId = 'items_grid_thumbnails_' . $thumbnails;
    }

    // Size of item's elements
    $size = $this->getData('size');
    if ($size !== null) {
        // For backward compatibility, convert old values to new values
        if ($size === 'size-s') {
            $size = 's';
        } elseif ($size === 'size-xs') {
            $size = 'xs';
        }

        $size = strtolower($size);
        $wrapperClasses .= ' size-' . $size;
    } else {
        if (isset($showItems)) {
            if ($showItems >= 8) {
                $wrapperClasses .= ' size-xs';
            } elseif ($showItems >= 6) {
                $wrapperClasses .= ' size-s';
            }
        }
    }

    // Align elements to the center
    if ($this->getData('centered')) {
        $wrapperClasses .= ' centered';
    }

    // Equal height of items
    if ($this->getData('equal_height')) {
        $wrapperClasses .= ' equal-height';
    }

    // Compile slider classes in one variable to get cleaner code
    $blockClasses = 'itemslider' . $sliderClasses . ' slider-arrows1 slider-arrows1-pos-top-right slider-pagination1';
    ?>
    <div class="cart-crosssell">
        <!--<div class="block-title title">
            <strong id="block- /* @escapeNotVerified *
            $class ?>-heading" role="heading" aria-level="2"> @escapeNotVerified *
                __('Großartiges Crosssell')  ?> */</strong>
        </div>-->
        <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */
        echo $class ?>-heading">
            <div class="products wrapper grid products-<?php /* @escapeNotVerified */
            echo $type; ?> products-carousel items-grid<?php if ($wrapperClasses) echo $wrapperClasses; ?>">
                <div id="<?php echo $sliderId; ?>" class="products list items product-items owl-carousel ">
                    <div class="products-list-item item product product-item  first-item">
                        <div class="inner-container">
                            <div class="item-text-wrapper">
                                <p class="item-text first"><?= __('Passend') ?></p>
                                <p class="item-text second"><?= __('zu deinen') ?></p>
                                <p class="item-text third"><?= __('Produkten') ?></p>
                            </div>
                        </div>
                    </div>
                    <?php
                    $iterator = 1;
                    $i = 0;
                    ?>
                    <?php foreach ($items as $_item): ?>

                        <?php $available = ''; ?>
                        <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php /*
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                */ ?>
                        <?php /// echo($iterator++ == 1) ? '<div class="item">' : '</div><div class="item">' ?>

                        <?php if ($numberOfRows > 1 && $i++ % $numberOfRows == 0): // Start a group of items (a slide) ?>
                            <div class="items-group">
                        <?php endif; ?>

                        <div class="products-list-item item">
                            <?php
                            $productNameEscaped = $block->escapeHtml($_item->getName());
                            ?>
                            <div class="product-item-info <?php /* @escapeNotVerified */
                            echo $available; ?>">
                                <div class="product-item-img">

                                    <a href="<?php /* @escapeNotVerified */
                                    echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">

                                        <?php if ($lazy && $numberOfRows < 2): ?>
                                            <img class="product-image-photo lazyOwl"
                                                 data-src="<?php echo $helperImage->getImageUrl($_item, $imageTypeId, $imgWidth, $imgHeight); ?>"
                                                 alt="<?php echo $productNameEscaped; ?>"/>
                                        <?php else: ?>
                                            <img class="product-image-photo"
                                                 src="<?php echo $helperImage->getImageUrl($_item, $imageTypeId, $imgWidth, $imgHeight); ?>"
                                                 alt="<?php echo $productNameEscaped; ?>"/>
                                        <?php endif; ?>

                                        <?php /*
                                <?php //echo $block->getImage($_item, $imageTypeId)->toHtml(); ?>
                                */ ?>
                                    </a>

                                </div>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" title="<?php echo $productNameEscaped; ?>"
                                           href="<?php /* @escapeNotVerified */
                                           echo $block->getProductUrl($_item) ?>">
                                            <?php echo $productNameEscaped; ?>
                                        </a>
                                    </strong>

                                    <?php /* @escapeNotVerified */
                                    //echo $block->getProductPrice($_item);?>
                                    <div class="price">
                                        <?= number_format($_item->getPrice(), 2, ',', '.') . ' &euro;' ?>
                                    </div>


                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <div class="field choice related">
                                                <input type="checkbox" class="checkbox related"
                                                       id="related-checkbox<?php /* @escapeNotVerified */
                                                       echo $_item->getId() ?>" name="related_products[]"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $_item->getId() ?>"/>
                                                <label class="label" for="related-checkbox<?php /* @escapeNotVerified */
                                                echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?></span></label>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product actions product-item-actions clearfix">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */
                                                                    echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?>">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?php /* @escapeNotVerified */
                                                                    echo $postData; ?>'
                                                                    type="button" title="<?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?>">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?php /* @escapeNotVerified */
                                                        echo $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                </div> <!-- end: product-item-details -->
                            </div> <!-- end: product-item-info -->
                        </div> <!-- end: item -->

                        <?php if ($numberOfRows > 1 && ($i % $numberOfRows == 0 || $i == $collectionSize)): // Close a group of items (a slide) ?>
                            </div> <!-- end: items-group -->
                        <?php endif ?>

                        <?php /// echo ($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div> <!-- end: element with the itemslider ID -->
                <div class="progress-container">
                    <a class="prev">
                    </a>
                    <div class="progress-bar">
                        <div class="progress"></div>
                    </div>
                    <a class="next">
                    </a>
                </div>
            </div> <!-- end: items-grid -->
        </div> <!-- end: block-content -->

    </div>
    <script type="text/javascript">
        //<![CDATA[

        requirejs(['jquery', 'owlcarousel'], function (jQuery, owl) {
            jQuery(function ($) {
                var owl = $('#<?php echo $sliderId; ?>');
                owl.owlCarousel({
                    lazyLoad: true,
                    responsive: true,
                    items: 5,
                    itemsDesktop: [1199, 4],
                    itemsDesktopSmall: [979, 3],
                    itemsMobile: [767, 2],
                    autoplay: false,
                    slideSpeed: <?php echo $speed; ?>,
                    scrollPerPage: true,

                    <?php if ($loop): ?>
                    rewindNav: true,
                    rewindSpeed: 600,
                    <?php else: ?>
                    rewindNav: false,
                    <?php endif; ?>
                    pagination: false,
                    navigation: false,
                    navigationText: false,
                    afterAction: afterActionFunc,
                    afterMove: afterMoveFunc

                });
                //console.log(owl.parent().find('.progress-container').find('.prev'));
                owl.parent().find('.progress-container').find('.prev').click(function () {
                    owl.trigger('owl.prev');
                });
                owl.parent().find('.progress-container').find('.next').click(function () {
                    owl.trigger('owl.next');
                });
                function afterMoveFunc() {
                    let that = owl.data('owlCarousel');
                    //let width = $(this).parent().find('.progress').css('width').replace(/[^-\d\.]/g, '');
                    var current = that.currentItem;
                    var amount = that.itemsAmount;
                    let bar = 0;
                    amount = amount - 4;
                    if (current !== 0) {
                        bar = current / amount * 100;
                    } else if(current === that.maximumItem) {
                        bar = 0;
                    } else if(current >= that.maximumItem - 4) {
                        bar = (that.maximumItem - 4) / amount * 100;
                    }
                    this.$elem.parent().find('.progress').css('margin-left', bar + '%');
                }
                function afterActionFunc() {
                    //get owl object
                    var that = this;

                    //get number of current slide (starting from 0)
                    var current = that.currentItem;
                    var amount = that.itemsAmount;
                    let bar = 0;
                    amount = amount - 4;
                    if (current === 0) {
                        bar = 1/ amount * 100;
                        this.$elem.parent().parent().find('.progress-container').find('.progress').css('width', bar + "%");
                    }

                    //console.log(current);
                }
            });
        });

        //]]>
    </script>
<?php endif; ?>