<?php
/**
 * @var \Dovo\Base\Block\Product\Properties $block
 */
?>
<?php
    $storeCode = $block->getStoreCode();
    $checker = '';
    if($storeCode === 'de') {
        $checker = 'Gutscheine';
    }
    if($storeCode === 'en') {
        $checker = 'Gift Cards';
    }
?>
<?php if((string)$block->getProductCategory() !== $checker): ?>
<div class="tidycal">
    <a href="https://tidycal.com/dovo"><span><?= __('Kostenfreie Telefon-Rasiermesserberatung buchen') ?></span></a>
</div>
<?php endif; ?>
