<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="content-wrap">
    <div class="logo">
        <a href="https://dovo.com">
            <img src="images/logo.svg"/>
        </a>
    </div>
    <div class="heading">
        <h1><?= __('Under Construction') ?></h1>
    </div>
    <div class="text">
        <p><?= __('Der DOVO Online-Shop ist in Kürze wieder für euch erreichbar. Bitte habt noch ein bisschen Geduld!') ?></p>
        <p><?= __('The DOVO online shop will be available again shortly. Please be patient!') ?></p>
    </div>
    <div class="back-action">
        <div class="backtohome">
            <a class="btn btn-basic"
               href="https://dovo.com"><span><?= __('Dovo Website') ?></span></a>
        </div>
    </div>
    <div class="social">
        <ul class="sm-banner">
            <li class="banner-item">
                <a class="facebook" href="https://www.facebook.com/DOVO.Stahlwaren/"><i
                            class="fa fa-facebook-square" aria-hidden="true"></i></a>
            </li>
            <li class="banner-item">
                <a class="instagram" href="https://www.instagram.com/dovo_solingen/"><i
                            class="fa fa-instagram" aria-hidden="true"></i></a>
            </li>
        </ul>
    </div>
    <div class="legal">
        <ul>
            <li><a href="https://dovo.com/impressum">Impressum</a></li>
            <li><a href="https://dovo.com/datenschutzerklaerung">Datenschutz</a></li>
        </ul>
    </div>
</div>
