<div class="block social-media">
    <div class="block-title social-media-title">
      <p><?= __('Besuche uns auf Social Media') ?></p>
    </div>
    <div class="block-content social-media-content">
        <ul>
            <li>
                <a href="https://www.facebook.com/DOVO.Stahlwaren/"><i class="fa fa-facebook-square"></i></a>
            </li>
            <li>
                <a href="https://www.instagram.com/dovo_solingen/"><i class="fa fa-instagram"></i></a>
            </li>
            <li>
                <a href="https://www.youtube.com/channel/UCt6b9nLK30sg0uer65yBXmA/featured/"><i
                        class="fa fa-youtube" aria-hidden="true"></i></a>
            </li>

        </ul>
    </div>
</div>
