<div class="block service">
    <div class="block-title service-title">
        <p><?php echo __('Kundenservice'); ?></p>
    </div>
    <div class="block-content service-content">
        <ul>
            <li>
                <a href="/kundenservice"><?php echo __('Hilfecenter'); ?></a>
            </li>
            <li>
                <a href="/chat"><?php echo __('Chat'); ?></a>
            </li>
        </ul>
    </div>
</div>