<div class="block social-media">
    <div class="block-title social-media-title">
      <p>Besuche uns auf Social Media</p>
    </div>
    <div class="block-content social-media-content">
        <ul>
            <li>
                <a href="https://www.facebook.com/DOVO.Stahlwaren/"><i class="fa fa-facebook-square"></i></a>
            </li>
            <li>
                <a href="https://www.instagram.com/dovo_solingen/"><i class="fa fa-instagram"></i></a>
            </li>
        </ul>
    </div>
</div>