<?php
/**
 * @var \Infortis\Base\Block\Html\Header $block
 */
?>
<?php
$theme = $block->getHelperTheme();

// //Get HTML of header blocks
// $storeSwitcherHtml = $block->getChildHtml('store_switcher');
// $copyrightHtml = $block->getChildHtml('copyright');
// $footerLinksHtml = $block->getChildHtml('footer_links');
// $cmsFooterLinksContainerHtml = $block->getChildHtml('cms_footer_links_container');
// $newsletterHtml = $block->getChildHtml('subscribe');
// $magentoDefaultFooterContainerHtml = $block->getChildHtml('footer');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID = $storeManager->getStore()->getCode();
$homepage = file_get_contents('https://dovo.marketingseals.com/api/footer.php?lang=' . $storeID);
?>
<div class="footer-container page-footer">
    <?= $homepage ?>
</div> <!-- end: footer-container -->
<script>
    require(['jquery'], function ($) {
        var form = $('.mc4wp-form');

        form.on('submit', function () {
            var email = form.find('input[type=email]').val();
            let params = {'email': email};
            $.ajax({
                showLoader: true,
                url: '/newsletter/subscriber/newaction',
                data: params,
                type: "POST",
                dataType: 'json'
            }).done(function (data) {
                //console.log(data);
            });
        });
    });
</script>
<script type="text/javascript">
    require(['jquery'], function ($) {
        var cookiePolicy = (function () {

            var $main = $('#cookie-notice');
            //var $toggle = $('.cn-set-cookie');
            var gaTrackDisable = 'gaTrackDisable';

            var init = function () {
                // Cookie Policy
                if (!getCookie('cookie_notice_accepted')) {
                    $main.addClass('visible');
                }


                $('.cn-set-cookie').click(function (e) {
                    e.preventDefault();

                    setCookie('cookie_notice_accepted', 'true', 365);

                    $main.removeClass('visible');

                });
            };

            /**
             *   set cookie
             *
             *   @param - {string} name
             *   @param - {string} value
             *   @param - {integer} days - cookie expiration
             *
             *   @return -
             */

            var setCookie = function (name, value, days) {
                var expires = "";

                if (days) {
                    var date = new Date();
                    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                    expires = "; expires=" + date.toGMTString();
                }

                document.cookie = name + "=" + value + expires + "; path=/";
            };


            /**
             *   get cookie value

             *   @param {string} name of cookie field
             *   @return {string} value
             */

            var getCookie = function (c_name) {
                if (document.cookie.length > 0) {
                    c_start = document.cookie.indexOf(c_name + "=");
                    if (c_start != -1) {
                        c_start = c_start + c_name.length + 1;
                        c_end = document.cookie.indexOf(";", c_start);
                        if (c_end == -1) {
                            c_end = document.cookie.length;
                        }
                        return unescape(document.cookie.substring(c_start, c_end));
                    }
                }
                return "";
            };

            var setGoogleAnalyticsToggle = function () {
                if (getCookie(gaTrackDisable) === "true") {
                    $toggle.prop('checked', false);
                } else {
                    $toggle.prop('checked', 'checked');
                }
            };

            var toggleGoogleAnalytics = function () {
                setCookie(gaTrackDisable, ($toggle.prop('checked')) ? false : true);
            };

            return {
                init: init,
                gaTrackDisable: gaTrackDisable,
                getCookie: getCookie
            };

        })();
        cookiePolicy.init();
    })
</script>