<div class="payment-methods">
    <div class="block-title">
        <strong><?= __('Wir akzeptieren') ?></strong>
    </div>
    <div class="block-content">
        <ul class="methods">
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/text-vorkasse.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/sepa.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/mastercard.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/visa.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/american-express-52.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/paypal-alternative2.png') ?>" />
            </li>
            <li>
                <img src="<?= $block->getViewFileUrl('images/payment/klarna-sofort.png') ?>" />
            </li>

        </ul>
    </div>
</div>