<?php
/**
 * Product list template
 *
 * @see \Dovo\ShopIndex\Block\MostPopular
 */
?>
<?php
 $mainCounter = 1;
?>
<section class="mostpopular-hobel">
    <div class="container">
        <?php $collection = $block->getMostViewed(); ?>
        <link rel="stylesheet"
              href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.carousel.min.css">
        <link rel="stylesheet"
              href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.theme.default.min.css">
        <script type="text/javascript"
                src="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/owl.carousel.js"></script>

        <div class="products-list hobel-carousel owl-carousel owl-theme"
             data-mage-init='{"Dovo_ShopIndex/js/mostpopular": {}}'>
            <?php
            $count = 1;
            foreach ($collection as $product) {
                if($count === $mainCounter) {
                    ?>
                    <div class="products-list-item first-item">
                        <div class="inner-container">
                            <p class="item-text first">Unsere</p>
                            <p class="item-text second">Besten</p>
                            <p class="item-text third">Rasierhobel</p>
                            <div class="actions">
                                <a href="/kategorie-2.html" class="action primary">
                                    <span>Alle Rasierhobel</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="products-list-item product">
                    <a class="product-link" href="<?= $product->getProductUrl(); ?>">
                        <div class="product-image-container">
                            <img class="product-image" src="<?php echo $block->getProductImage($product->getId()); ?>"
                                 max-height="260" max-width="260" alt="mostpopular-list-item"/>
                        </div>
                        <div class="product-info-container">
                            <div class="product-name">
                                <?= $product->getName(); ?>
                            </div>
                            <div class="price">
                                <?= number_format($product->getPrice(), 2, ',', '.') . ' &euro;'; ?>
                            </div>
                        </div>
                    </a>
                </div>
                <?php
                $count ++;
            }
            foreach ($collection as $product) {
                ?>
                <div class="products-list-item product">
                    <a class="product-link" href="<?= $product->getProductUrl(); ?>">
                        <div class="product-image-container">
                            <img class="product-image" src="<?php echo $block->getProductImage($product->getId()); ?>"
                                 max-height="260" max-width="260" alt="mostpopular-list-item"/>
                        </div>
                        <div class="product-info-container">
                            <div class="product-name">
                                <?= $product->getName(); ?>
                            </div>
                            <div class="price">
                                <?= number_format($product->getPrice(), 2, ',', '.') . ' &euro;'; ?>
                            </div>
                        </div>
                    </a>
                </div>
                <?php
                $count ++;
            }
            ?>
        </div>
        <div class="progress-container">
            <a class="prev">
            </a>
            <div class="progress-bar">
                <div class="progress"></div>
            </div>
            <a class="next">
            </a>
        </div>
    </div>

</section>